name: GSI Build

on: [push]
    
env:
  ROM_URL: https://cfhcable.dl.sourceforge.net/project/xiaomi-eu-multilang-miui-roms//xiaomi.eu/MIUI-WEEKLY-RELEASES/20.7.2/xiaomi.eu_multi_MI9SE_20.7.2_v12-10.zip
  ROM_NAME: MIUI
  ZIP_NAME: miui-eu
  TZ: America/Sao_Paulo
  MIR: gof
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Install python requirements
         run: |
              pip install pyrogram tgcrypto

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs -b master

       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Download ROM & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME

       - name: Zip A only and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z          

       - name: Zip AB and upload 
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              ./transfer $MIR ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      

       - name: Create env variable CAT_FILE
         run: echo "::set-env name=CAT_FILE::$(cat ErfanGSIs/output/*-Aonly-*.txt)"

       - name: Print A-Only build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt

       - name: Send build info to Telegram
         env:
              chat_id: ${{ secrets.CHAT_ID }}
              bot_token: ${{ secrets.BOT_TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}
         run: |
              python .github/workflows/bot.py