name: GSI Build

on: [push]
    
env:
  ROM_URL: http://otafsc1.h2os.com/patch/CHN/OnePlus7THydrogen/OnePlus7THydrogen_13.X.07_007_2007030048/OnePlus7THydrogen_13.X.07_OTA_007_all_2007030048_96dc7.zip
  ROM_NAME: OxygenOS
  TZ: America/Sao_Paulo
  MIR: gof
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x build/initial.sh
              . build/initial.sh

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/yukosky/ErfanGSIs -b runner

       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Print A-Only build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt
